<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarelibre [
    <!ELEMENT softwarelibre (programas, licencias)>
    <!ELEMENT programas (programa+)>
    <!ELEMENT programa (version+)>
    <!ELEMENT version (#PCDATA)>
    <!ELEMENT licencias (licencia*)>
    <!ELEMENT licencia (#PCDATA)>
    <!ATTLIST licencia nombre ID #REQUIRED>
    <!ATTLIST version nombre NMTOKEN #REQUIRED>
    <!ATTLIST version licencia CDATA #REQUIRED>
    <!ATTLIST version fechapublicacion CDATA #IMPLIED>
    <!ATTLIST programa nombre CDATA #REQUIRED>
]>
<softwarelibre>
    <programas>
        <programa nombre="Inkscape">
            <version nombre="0.47" licencia="GPL_v2" fechapublicacion="17/08/2010"/>
            <version nombre="0.48" licencia="GPL_v2" fechapublicacion="17/08/2010"/>
            <version nombre="0.48.2" licencia="GPL_v2" fechapublicacion="14/08/2011"/>
        </programa>
        <programa nombre="PostgreSQL">
            <version nombre="9.1.0" licencia="BSD2" fechapublicacion="15/09/2011"/>
            <version nombre="9.1.3" licencia="BSD2"/>
        </programa>
    </programas>
    <licencias>
        <licencia nombre="GPL_v2"/>
        <licencia nombre="BSD2"/>
        <licencia nombre="Apache_v2"/>
    </licencias>
</softwarelibre>
